languange: java

before_install:
  - git submodule update --init --remote
  - automation/replace_ebr_groupids.sh com.runolarity.osgi.bundles

install: 
  - mvn -f ebr/pom.xml install -DskipTests=true

script: true 
