languange: java
sudo: false

jdk:
- oraclejdk8

before_install:
- wget https://archive.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.zip
- unzip -qq apache-maven-3.3.9-bin.zip
- export M2_HOME=$PWD/apache-maven-3.3.9
- export PATH=$M2_HOME/bin:$PATH
- echo "MAVEN_OPTS='-Xmx1g -Dorg.slf4j.simpleLogger.showDateTime=true -Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss:SSS'" > ~/.mavenrc

install:
- mvn -f ebr/releng/maven-plugins/pom.xml install
- mvn -f ebr/recipes/pom.xml install
- mvn -f ebr/releng/p2/pom.xml package

script: true

deploy:
  provider: s3
  access_key_id: AKIAIXAT4M2U6R74C3DA
  secret_access_key:
    secure: bd6TedUn/Qb9huNX960yREuVjxuxM8DsdEkx1ZB/Lf1hZ3+Q2AcxwZFuZUMijj3wV9l5BH4wZdTv/B7B5RtGtBP0dOykWkw3BMXovqHgHH360scw+2O7sAc3M+55MfOt2Mg0KLE2Y7lEuDQb1hJ8Ux3jCzLkTudrv1D+ktc0pZE=
  bucket: public.runolarity.com
  local-dir: ebr/releng/p2/repository/target/repository
  upload-dir: repository
